spring.application.name=bjj-api

# Configuração da Conexão com o MySQL (substitua a senha se o seu banco tiver uma)
spring.datasource.url=jdbc:mysql://localhost:3306/bjj?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configurações do Hibernate / JPA para o Spring Boot
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect